### ISSUE TITLE
Lizenz

### ISSUE THREAD

**Issue by DavidRisch** [JoWagnerAtLimagoDe/eTeach_TINF18IT1#1]
Aus `ATmega48A-PA-88A-PA-168A-PA-328-P-DS-DS40002061A.pdf`:
```
No licenses are conveyed, implicitly or otherwise, under any Microchip intellectual property rights unless otherwise stated.
```
Dies pdf (und vermutlich auch nano.jpg und nano2.jpg) dürfen also nicht einfach unter Apache-2.0 lizenziert werden.

**Comment by JoWagnerAtLimagoDe** [comment]
Ok. Danke für den Hinweis. Da habe ich nicht aufgepasst als ich das Repo angelegt habe.. dann fliegen die Bilder nachher wieder raus..

Am 14. April 2020 14:50:56 MESZ schrieb DavidRisch <notifications@github.com>:
>Aus `ATmega48A-PA-88A-PA-168A-PA-328-P-DS-DS40002061A.pdf`:>
>```>
>No licenses are conveyed, implicitly or otherwise, under any Microchip
>intellectual property rights unless otherwise stated.>
>```>
>Dies pdf (und vermutlich auch nano.jpg und nano2.jpg) dürfen also nicht
>einfach unter Apache-2.0 lizenziert werden.>
>>
>-- >
>You are receiving this because you are subscribed to this thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/JoWagnerAtLimagoDe/eTeach_TINF18IT1/issues/1

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
